# Generated by Django 3.0.3 on 2020-02-15 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł serialu')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Rok wydania')),
                ('platform', models.IntegerField(choices=[(1, 'Netflix'), (2, 'HBO'), (3, 'Inne')], default=3, verbose_name='Gdzie znajde')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows', models.ManyToManyField(related_name='recommendations_set', to='ratings.Show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Ocena')),
                ('comment', models.TextField(max_length=250, verbose_name='Komentarz do oceny')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
