# Generated by Django 3.0.3 on 2020-02-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratings_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Komentarz do oceny'),
        ),
    ]
