# Generated by Django 3.0.3 on 2020-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20200215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Komentarz do oceny'),
        ),
    ]
