# Generated by Django 3.0.3 on 2020-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20200215_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Rok wydania'),
        ),
    ]
